
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */ import { User } from "./User";
/* do not edit */ 
/* do not edit */ export enum ActivityType {
/* do not edit */     CHAT_MESSAGE = "CHAT_MESSAGE",
/* do not edit */     COURSE_MESSAGE = "COURSE_MESSAGE",
/* do not edit */     ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED",
/* do not edit */     ASSIGNMENT_RETURNED = "ASSIGNMENT_RETURNED",
/* do not edit */     ASSIGNMENT_SUBMITTED = "ASSIGNMENT_SUBMITTED",
/* do not edit */     FILE_UPLOADED = "FILE_UPLOADED",
/* do not edit */     EVENT_CREATED = "EVENT_CREATED",
/* do not edit */     CONFERENCE_STARTED = "CONFERENCE_STARTED",
/* do not edit */     INCOMING_CALL = "INCOMING_CALL",
/* do not edit */     MISSED_CALL = "MISSED_CALL",
/* do not edit */ }
/* do not edit */ 
/* do not edit */ export const ActivitySettings: {
/* do not edit */     [k in ActivityType]: {
/* do not edit */         persistent: boolean;
/* do not edit */         pushNotification: boolean;
/* do not edit */     };
/* do not edit */ } = {
/* do not edit */     ASSIGNMENT_CREATED: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: false,
/* do not edit */     },
/* do not edit */     ASSIGNMENT_RETURNED: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: false,
/* do not edit */     },
/* do not edit */     ASSIGNMENT_SUBMITTED: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: false,
/* do not edit */     },
/* do not edit */     CHAT_MESSAGE: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: true,
/* do not edit */     },
/* do not edit */     COURSE_MESSAGE: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: true,
/* do not edit */     },
/* do not edit */     CONFERENCE_STARTED: {
/* do not edit */         persistent: false,
/* do not edit */         pushNotification: true,
/* do not edit */     },
/* do not edit */     EVENT_CREATED: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: false,
/* do not edit */     },
/* do not edit */     FILE_UPLOADED: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: false,
/* do not edit */     },
/* do not edit */     INCOMING_CALL: {
/* do not edit */         persistent: false,
/* do not edit */         pushNotification: true,
/* do not edit */     },
/* do not edit */     MISSED_CALL: {
/* do not edit */         persistent: true,
/* do not edit */         pushNotification: true,
/* do not edit */     },
/* do not edit */ };
/* do not edit */ 
/* do not edit */ 
/* do not edit */ export class Activity {
/* do not edit */     
/* do not edit */     id: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     itemId: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     type: ActivityType;
/* do not edit */ 
/* do not edit */     
/* do not edit */     
/* do not edit */     users: User[];
/* do not edit */ 
/* do not edit */     
/* do not edit */     
/* do not edit */     date: Date;
/* do not edit */ 
/* do not edit */     persistent: boolean;
/* do not edit */     pushNotification: boolean;
/* do not edit */     payload: any;
/* do not edit */ }
/* do not edit */