
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */ import { Grade } from "./Grade";
/* do not edit */ 
/* do not edit */ 
/* do not edit */ export class Assignment {
/* do not edit */   
/* do not edit */   public id: number;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public title: string;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public content: string;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public grade: Grade;
/* do not edit */ }
/* do not edit */