
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export enum Buckets {
/* do not edit */     ASSIGNMENTS = "assignments",
/* do not edit */     CHAT_FILES = "chatfiles",
/* do not edit */     COURSE_FILES = "coursefiles",
/* do not edit */     LOGS = "logs",
/* do not edit */ }
/* do not edit */