
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */ import { User } from "./User";
/* do not edit */ 
/* do not edit */ 
/* do not edit */ export class Conference {
/* do not edit */     
/* do not edit */     public id: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     
/* do not edit */     public created: Date;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public started: Date;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public type: "private" | "group" | "course";
/* do not edit */ 
/* do not edit */     
/* do not edit */     
/* do not edit */     public users: User[];
/* do not edit */ }
/* do not edit */