
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export enum EventCategory {
/* do not edit */     Assignment,
/* do not edit */     UserEvent,
/* do not edit */     TeacherEvent,
/* do not edit */     Conference,
/* do not edit */ }