
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export type Holiday = {
/* do not edit */     name: string;
/* do not edit */     startDate: Date;
/* do not edit */     endDate: Date;
/* do not edit */     isVacation: boolean;
/* do not edit */ }
/* do not edit */ 
/* do not edit */ export type HolidayData = {
/* do not edit */     [year: number]: Holiday[];
/* do not edit */ }
/* do not edit */