
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */ import { User } from "./User";
/* do not edit */ import { MessageStatus } from "./MessageStatus";
/* do not edit */ import { Chat } from "./Chat";
/* do not edit */ import { Course } from "./Course";
/* do not edit */ 
/* do not edit */ 
/* do not edit */ export class Message {
/* do not edit */   
/* do not edit */   public id: number;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public text: string;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public sender: User;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public edited?: boolean;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public citation?: number;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public date: Date;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public chat: Chat;
/* do not edit */ 
/* do not edit */   
/* do not edit */   public course: Course;
/* do not edit */ 
/* do not edit */   public reactions?: Record<string, User[]>;
/* do not edit */   public fromMe?: boolean;
/* do not edit */   public status?: MessageStatus;
/* do not edit */ }
/* do not edit */