
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export enum MessageStatus {
/* do not edit */   Waiting = "Waiting",
/* do not edit */   Sent = "Sent",
/* do not edit */   Delivered = "Delivered",
/* do not edit */   Seen = "Seen",
/* do not edit */ }
/* do not edit */