
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export enum NotificationCategory {
/* do not edit */     ChatMessage = "ChatMessage",
/* do not edit */     NewAssignment = "NewAssignment",
/* do not edit */     IncomingCall = "IncomingCall",
/* do not edit */     AddedToCourse = "AddedToCourse",
/* do not edit */ }
/* do not edit */