
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ import { ActivityType } from "./Activity";
/* do not edit */ 
/* do not edit */ export type PushNotificationInfo = {
/* do not edit */     title: string,
/* do not edit */     body: string,
/* do not edit */ }
/* do not edit */ export type PushNotificationData = {
/* do not edit */     silent?: boolean,
/* do not edit */     subtitle?: string,
/* do not edit */     color?: string,
/* do not edit */     image?: string,
/* do not edit */     thumbnail?: string,
/* do not edit */     channel?: string,
/* do not edit */     type: ActivityType,
/* do not edit */     payload?: string;
/* do not edit */     [key: string]: any,
/* do not edit */ };
/* do not edit */ 
/* do not edit */ export type PushNotification = {
/* do not edit */     data: PushNotificationData,
/* do not edit */     notification: PushNotificationInfo,
/* do not edit */     priority: string,
/* do not edit */     from: string,
/* do not edit */ };
/* do not edit */