
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface SchedulerEvent {
/* do not edit */     Id: number;
/* do not edit */     Subject: string;
/* do not edit */     Description: string;
/* do not edit */     Location: string;
/* do not edit */     StartTime: Date;
/* do not edit */     EndTime: Date;
/* do not edit */     IsAllDay: boolean;
/* do not edit */     StartTimezone: string;
/* do not edit */     EndTimezone: string;
/* do not edit */     RecurrenceRule: string;
/* do not edit */     Color: string;
/* do not edit */ }