
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export enum SocketEvent {
/* do not edit */     USER_ONLINE_STATUS = "USER_ONLINE_STATUS",
/* do not edit */     USER_TYPING_STATUS = "USER_TYPING_STATUS",
/* do not edit */     ACTIVE_CHAT = "ACTIVE_CHAT"
/* do not edit */ }
/* do not edit */ 
/* do not edit */ export interface USER_ONLINE_STATUS_PAYLOAD {
/* do not edit */     userId: string;
/* do not edit */     online: boolean;
/* do not edit */ }
/* do not edit */ 
/* do not edit */ export interface USER_TYPING_STATUS_PAYLOAD {
/* do not edit */     username: string,
/* do not edit */     typing: boolean,
/* do not edit */ }
/* do not edit */ 
/* do not edit */ export interface ACTIVE_CHAT_PAYLOAD {
/* do not edit */     chatId: string | null;
/* do not edit */ }