
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */ 
/* do not edit */
/* do not edit */ 
/* do not edit */ 
/* do not edit */ export class User {
/* do not edit */   
/* do not edit */   public id: number;
/* do not edit */
/* do not edit */   
/* do not edit */   public username: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public role: "student" | "teacher" | "admin";
/* do not edit */
/* do not edit */   
/* do not edit */   public password: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public passwordResetToken: string;
/* do not edit */
/* do not edit */   
/* do not edit */   
/* do not edit */   public createdAt: Date;
/* do not edit */
/* do not edit */   
/* do not edit */   
/* do not edit */   public updatedAt: Date;
/* do not edit */
/* do not edit */   
/* do not edit */
/* do not edit */   public jwtToken?: string;
/* do not edit */
/* do not edit */   
/* do not edit */ }
