### Project Information ###
site_name: SchoolSquirrel Docs
site_url: https://schoolsquirrel.github.io
site_author: Hannes Rüger
site_description: >-
    SchoolSquirrel - Die Platform für digitalen Unterricht.
    Mit Chat, Aufgaben, Video-Konferenzen und mehr!
copyright: Copyright &copy; 2019 - 2020 Hannes Rüger


### Repository ###
repo_name: SchoolSquirrel
repo_url: https://github.com/SchoolSquirrel/SchoolSquirrel
edit_uri: edit/master/docs/docs


### Navigation ###
nav:
    - Home:
        - index.md
    - Über:
        - about/index.md
    - Schüler:
        - Login: students/login.md
        - Aufgaben: students/assignments.md
    - Lehrer:
        - Login: teachers/login.md
        - Aufgaben: teachers/assignments.md
    - Administratoren:
        - Login: admins/login.md
        - Aufgaben: admins/assignments.md


### Extra Configuration ###
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/SchoolSquirrel
      - icon: fontawesome/brands/docker
        link: https://hub.docker.com/r/schoolsquirrel/schoolsquirrel


### Theme Configuration ###
theme:
    name: material
    features:
        - tabs


### Plugin Configuration ###
plugins:
    - search
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences