name: Build

on: [push]

jobs:
  build_api:
    name: API Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      working-directory: api
      run: npm i
    - name: Build
      working-directory: api
      run: npm run build
  build_web:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      working-directory: SchoolSquirrel
      run: npm i
    - name: Build
      working-directory: SchoolSquirrel
      run: npm run web:build
  build_docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install frontend dependencies
      working-directory: SchoolSquirrel
      run: npm i
    - name: Install backend dependencies
      working-directory: api
      run: npm i
    - name: Build
      working-directory: docker
      run: sudo bash ./build.sh
    - name: Deploy to Docker Hub
      working-directory: docker
      run: sudo bash ./deploy.sh ${{ secrets.DOCKER_HUB_USERNAME }} ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  build_android:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup Nativescript
      uses: hrueger/setup-nativescript@v1.0.0
    - name: Install frontend dependencies
      working-directory: SchoolSquirrel
      run: npm i
    - run: 'echo "$GOOGLE_SERVICES_JSON" | base64 --decode > App_Resources/Android/google-services.json'
      shell: bash
      working-directory: SchoolSquirrel
      env:
        GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
    - name: Build
      working-directory: SchoolSquirrel
      run: npm run mobile:android:build
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: schoolsquirrel-android
        path: SchoolSquirrel/platforms/android/app/build/outputs/apk/debug/app-debug.apk
    