name: Docs

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material
    - name: Build docs
      working-directory: docs
      run: mkdocs build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: docs/site
        TARGET_FOLDER: docs
        REPOSITORY_NAME: SchoolSquirrel/schoolsquirrel.github.io
