name: Docs

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material mkdocs-exclude
    - name: Build API Docs
      working-directory: scripts
      run: npm install && npm run update-api-definitions
    - name: Build docs
      working-directory: docs
      run: mkdocs build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        BRANCH: gh-pages
        FOLDER: docs/site
        GIT_CONFIG_NAME: schoolsquirrel-bot
        GIT_CONFIG_EMAIL: team.schoolsquirrel@gmail.com
  check:
    name: Check for dead links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
      working-directory: scripts
    - name: Check links
      working-directory: scripts
      run: npm run check-docs-links