name: Docs

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material
    - name: Build docs
      working-directory: docs
      run: mkdocs build
    - name: Deploy
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_ACCESS_TOKEN }}
        directory: docs/site
        repository: SchoolSquirrel/schoolsquirrel.github.io
